[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend-api && npm install"]

[phases.build]
cmds = ["cd backend-api && npm run build"]

[start]
cmd = "cd backend-api && npm start"
